"""Add barista models

Revision ID: 4dba7c4f7495
Revises: b1c2d3e4f5a6
Create Date: 2026-07-02 12:45:23.557094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dba7c4f7495'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barista_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('relationship_stage', sa.String(length=50), nullable=True),
    sa.Column('has_completed_onboarding', sa.Boolean(), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('pace_preference', sa.String(length=50), nullable=True),
    sa.Column('favorite_categories_cache', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('barista_interaction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('mood_tag', sa.String(length=50), nullable=True),
    sa.Column('book_recommended_id', sa.Integer(), nullable=True),
    sa.Column('user_response', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_recommended_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_progress_book_id'))
        batch_op.drop_index(batch_op.f('ix_reading_progress_user_id'))

    op.drop_table('reading_progress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('paragraph_index', sa.INTEGER(), nullable=False),
    sa.Column('total_paragraphs', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_progress_book_id'), ['book_id'], unique=False)

    op.drop_table('barista_interaction_log')
    op.drop_table('barista_profile')
    # ### end Alembic commands ###
