"""add membership_expires_at

Revision ID: 54b5dc06e6dd
Revises: a833e6299f0f
Create Date: 2026-06-23 15:34:47.646567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b5dc06e6dd'
down_revision = 'a833e6299f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_column('membership_expires_at')

    # ### end Alembic commands ###
