"""Add renewal_status to transactions

Revision ID: c098f87da85d
Revises: 3e6b60183b97
Create Date: 2026-06-22 12:31:39.038271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c098f87da85d'
down_revision = '3e6b60183b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renewal_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('renewal_status')

    # ### end Alembic commands ###
