"""add_finn_extra_fields

Revision ID: c2b5e7f8a9b0
Revises: 4dba7c4f7495
Create Date: 2026-07-05 12:00:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "c2b5e7f8a9b0"
down_revision = "4dba7c4f7495"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "barista_profile",
        sa.Column("skill_level", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "barista_profile",
        sa.Column("reading_count", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("barista_profile", "reading_count")
    op.drop_column("barista_profile", "skill_level")
    # ### end Alembic commands ###
