"""add_performance_indexes

Revision ID: d50bb92718aa
Revises: 760ad1391051
Create Date: 2026-06-30 00:19:49.231049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50bb92718aa'
down_revision = '760ad1391051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_author_name'), ['name'], unique=False)

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_title'), ['title'], unique=False)

    with op.batch_alter_table('book_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_transaction_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_transaction_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_transaction_fine_paid'), ['fine_paid'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_transaction_issued_at'), ['issued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_transaction_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_transaction_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_user_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_status'))
        batch_op.drop_index(batch_op.f('ix_reservation_created_at'))
        batch_op.drop_index(batch_op.f('ix_reservation_book_id'))

    with op.batch_alter_table('book_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_book_transaction_status'))
        batch_op.drop_index(batch_op.f('ix_book_transaction_issued_at'))
        batch_op.drop_index(batch_op.f('ix_book_transaction_fine_paid'))
        batch_op.drop_index(batch_op.f('ix_book_transaction_due_date'))
        batch_op.drop_index(batch_op.f('ix_book_transaction_book_id'))

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_title'))
        batch_op.drop_index(batch_op.f('ix_book_rating'))
        batch_op.drop_index(batch_op.f('ix_book_created_at'))
        batch_op.drop_index(batch_op.f('ix_book_category_id'))
        batch_op.drop_index(batch_op.f('ix_book_author_id'))

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_author_name'))

    # ### end Alembic commands ###
