"""add barista preference learning and feedback fields

Revision ID: e7496d333b6a
Revises: dc8762fd6708
Create Date: 2026-07-06 18:02:27.214581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7496d333b6a'
down_revision = 'dc8762fd6708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barista_interaction_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reaction', sa.String(length=30), nullable=True))

    with op.batch_alter_table('barista_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_weights', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('author_weights', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preference_version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_voice_fragments', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barista_profile', schema=None) as batch_op:
        batch_op.drop_column('last_voice_fragments')
        batch_op.drop_column('preference_version')
        batch_op.drop_column('author_weights')
        batch_op.drop_column('genre_weights')

    with op.batch_alter_table('barista_interaction_log', schema=None) as batch_op:
        batch_op.drop_column('reaction')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
